name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone simplescripts
        run: |
          git clone https://github.com/johnlindquist/simplescripts.git ~/.simplesdk
          
      - name: npm install
        run: |
          ~/.simplesdk/setup/install-node.sh --prefix ~/.simplesdk/node
          ~/.simplesdk/node/bin/npm install --prefix ~/.simplesdk
          ~/.simplesdk/node/bin/npm install @octokit/rest --prefix ~/.simplesdk
          
          
      - name: create tag
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          SIMPLE_PATH: ~/.simple
        run: |
           ~/.simplesdk/simple.sh ~/.simplesdk/setup/create-tag.js v0.0.8                                                                                              
        
