# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone simplescripts
        run: |
          git clone https://github.com/johnlindquist/simplescripts.git ~/.simplesdk
          ls ~/.simplesdk
          
      - name: Install latest node
        run: >
          ~/.simplesdk/setup/install-node.sh --prefix ~/.simplesdk/node
          
      - name: npm install
        run: |
          cd ~/.simplesdk
          ~/.simplesdk/node/bin/npm install --prefix ~/.simplesdk
          
      - name: create tag
        run: |
          cd ~/.simplesdk
          SIMPLE_PATH=~/.simple ~/.simplesdk/simple.sh ~/.simplesdk/setup/create-tag.js "v0.0.2"                                                                                                        
        
