name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone simplescripts
        run: |
          git clone https://github.com/johnlindquist/simplescripts.git ~/.simplesdk
          
      - name: npm install
        run: |
          cd ~/.simplesdk
          ./setup/install-node.sh --prefix ./node
          ./node/bin/npm install --prefix ./
          ./node/bin/npm install @octokit/rest --prefix ./
          
          
      - name: create tag
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          cd ~/.simplesdk
          ./simple.sh ./setup/create-tag.js v0.0.9                                                                                              
        
